spring.application.name=limited

spring.data.redis.cluster.nodes=${REDIS_CLUSTER_NODES:localhost:7000,localhost:7001,localhost:7002,localhost:7003,localhost:7004,localhost:7005}
spring.data.redis.timeout=${REDIS_TIMEOUT:1s}

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3307/limited_reservation}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=${JPA_DATABASE_PLATFORM:org.hibernate.dialect.MySQLDialect}
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.open-in-view=false
