spring.application.name=limited

spring.data.redis.cluster.nodes=${REDIS_CLUSTER_NODES:localhost:7000,localhost:7001,localhost:7002,localhost:7003,localhost:7004,localhost:7005}
spring.data.redis.timeout=${REDIS_TIMEOUT:1s}

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3307/limited_reservation}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=${JPA_DATABASE_PLATFORM:org.hibernate.dialect.MySQLDialect}
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.open-in-view=false

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
app.kafka.booking-events-topic=${BOOKING_EVENTS_TOPIC:booking-events}
app.outbox.publisher-fixed-delay=${OUTBOX_PUBLISHER_FIXED_DELAY:1000}
app.outbox.max-retry-count=${OUTBOX_MAX_RETRY_COUNT:5}

app.checkout-cache.max-ttl=${CHECKOUT_CACHE_MAX_TTL:10m}
app.checkout-cache.warmup-fixed-delay=${CHECKOUT_CACHE_WARMUP_FIXED_DELAY:60000}
app.checkout-cache.warmup-limit=${CHECKOUT_CACHE_WARMUP_LIMIT:100}
